### ISSUE TITLE
RFC: Drop “Receive to P2TR” from website

### ISSUE THREAD

**Issue by Xekyo** [sbddesign/bech32m-adoption#21]
Given that we want to focus on sending support, should we perhaps drop the “Receive to P2TR” column? If we did, we could transform the unwieldy table into just two sections of “Can already send to bech32m” and “Cannot send to bech32m” and just put logos there. That would make it much easier to get an overview, and we could use happy/sad bunnies.

**Comment by sbddesign** [comment]
I went ahead and pushed a commit that just removes the receive column. Also, earlier today, I pushed another commit that adds a filter where you can toggle just "senders" and "non-senders". We could easily re-enable the receive column at a later date.

Also, the simple dichotomy of just having two separate tables is kind of nice, at least for the first round. I don't know if I want to start adding logos, as that's going to be a lot of hunting, and then I'll feel the need to add a logo whenever somebody tests a project that wasn't already in the table. But I like the idea of just two separate pools and then using happy and sad bunnies.

**Comment by sbddesign** [comment]
I think it would be good to do a Figma mock of this idea before diving into the code.

**Comment by Xekyo** [comment]
What do you think about just the names then, instead of logos? Could you make netlify output a new preview with the single column? I'd be curious what it looks like.

**Comment by sbddesign** [comment]
It should already display single columns: https://whentaproot.netlify.app/#support

<img width="1650" alt="Screen Shot 2022-09-20 at 11 10 39 PM" src="https://user-images.githubusercontent.com/2414177/191405946-db513e02-8a41-4e09-a39f-8c34fc64fa8f.png">

Working on the alternative look here: https://www.figma.com/file/dE1HQN864N68jca79VUKNw/When-Taproot?node-id=227%3A3216

**Comment by sbddesign** [comment]
Done
